################################################################################
# Core: shared constants and low-level utilities
#
# Definitions shared across retrieval, fusion, caching, and segmentation.
# The default stage sequence is implemented by boundary_delineation().
#
# rs structure:
#   spec      list -- user-supplied query: point (lon/lat), dates, dims,
#                    index_name, max_cloud_cover, scl_classes
#   geom      list -- derived spatial: bbox, source, pixel_size_m,
#                    nr, nc, centre_rc
#   scenes    list -- per-date {date, bands, index, item_assets} for
#                    index_name; user-extractable
#   internals list -- internal detection data: feature_stack, feat_array,
#                    mu, detection_scenes (search_index material when
#                    different from index_name)
#   state     list -- matrix carriers: alive_mat, decided_mat
#   params    list -- full populated rs_params list; auto-applied by every
#                    pipeline stage. Stage call-site overrides (params arg,
#                    inline named args) apply for that call only and do not
#                    mutate rs$params.
#
# Pipeline-execution state (pre-cleanup pending flags) is carried as
# attr(rs, "pending"), kept off the visible structure.
#
# Class: "ocular". Tested via is_rs(x).
#
################################################################################

## Derive unsupported fusion indices from the actual fine/coarse lookup
## pair. A function (not a constant) avoids relying on file collation order.
.fusionUnsupportedIndices <- function(){
  ln <- tryCatch(names(landsat_index_list), error = function(e) character(0))
  mn <- tryCatch(names(mcd43a4_index_list), error = function(e) character(0))
  return(setdiff(ln, mn))
}
.S2_START        <- as.Date("2015-07-01")
.L8_START        <- as.Date("2013-04-01")
.STAC_ENDPOINT   <- "https://planetarycomputer.microsoft.com/api/stac/v1"

`%||%` <- function(a, b) if (is.null(a)) b else a

## Replace NaN/Inf generated by ratio indices at zero denominators with NA.
.finiteIndex <- function(r){
  terra::ifel(is.finite(r), r, NA)
}

## Stable, dependency-free content digest for cache keys. Serialising the
## payload (rather than deparsing it) keeps names, types, and nested lists in
## the fingerprint. Four modular rolling hashes avoid temporary files and do
## not require filesystem access.
.stableHash <- function(payload){
  bytes <- as.integer(serialize(payload, NULL, version = 2))
  modulus <- c(2147483629, 2147483587, 2147483579, 2147483563)
  multiplier <- c(257, 263, 269, 271)
  seed <- c(17, 29, 43, 61)
  pieces <- vapply(seq_along(modulus), function(i){
    h <- seed[[i]]
    for( b in bytes ) h <- (h * multiplier[[i]] + b + 1) %% modulus[[i]]
    sprintf("%08x", as.integer(h))
  }, character(1L))
  paste0(pieces, collapse = "")
}
